image: Visual Studio 2019

version: 1.0.{build}

environment:
  ftp_user:
    secure: Z75wFmcHy1L3BjtFSYLKiw==
  ftp_password:
    secure: zp5Jc9evLD418f9gRNQ/Aw==
  config1:
    secure: Ps4/0xp/ynjCQPZ8ABmpA+j7BG1ErS3wrqvpmLy7HA3y0hpVxQbrqN/4nFVpPvpC
  config2:
    secure: lBUg3wgeQWhthz06T/iCabNhj5G0mXWYF5udbfdZ92E=

before_build:
  - nuget restore src

build_script:
  - dotnet publish "src\AddBook.sln" --framework netcoreapp2.0 --configuration Release --output "./Publish" /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test: off

artifacts:
- path: Publish

before_deploy:
- ps: .\Clear-FtpDirectory.ps1

deploy_script:
- ps: .\Publish.ps1
