version: 1.0.{build}

environment:
  ftp_password:
    secure: eK/zCvZEGU6BcRfo1CoYnlrLD7SoyaUyOb3aIq8CkmQ=

before_build:
  - nuget restore

build:
  - msbuild "src\AddBook.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:PublishProfile=appveyor /p:Password=%ftp_password%

test: off

artifacts:
- path: src/Publish
  name: compiled_site
