image: Visual Studio 2022

version: 1.0.{build}

environment:
  ftp_user:
    secure: Z75wFmcHy1L3BjtFSYLKiw==
  ftp_password:
    secure: zp5Jc9evLD418f9gRNQ/Aw==
  config1:
    secure: BZwan3nbCiJ9SqjZ6NXMTIRcGpIiHu3x7vsl3ZFVMJkuSVTX2m5tKpgarW4NdnQb
  config2:
    secure: lBUg3wgeQWhthz06T/iCabNhj5G0mXWYF5udbfdZ92E=

before_build:
  - nuget restore src

build_script:
  - dotnet publish "src\AddBook.sln" --framework net6.0 --configuration Release --property:PublishDir="./Publish" /logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test: off

artifacts:
- path: Publish

before_deploy:
- ps: .\Clear-FtpDirectory.ps1

deploy_script:
- ps: .\Publish.ps1
