version: 1.0.{build}

environment:
  ftp_password:
    secure: eK/zCvZEGU6BcRfo1CoYnlrLD7SoyaUyOb3aIq8CkmQ=
  access_token:
    secure: CF5fbrJvzIdoFSlDdW4c5NQUzca/B75Bxqp9kwCvp5yksTLiUxaDzhh0WsmLXp4P

test: off

artifacts:
- path: src/Publish
  name: compiled_site
