image: Visual Studio 2022

version: 1.0.{build}

environment:
  ftp_user:
    secure: qFoKIg/opgBgjdrHAZlFOA==
  ftp_password:
    secure: 6wrMkWW2J1r3Yhg4o1bfxkuIKwNG05EW0ZkpryokBzI=

install:
  - choco upgrade pretzel -y
  - choco upgrade pretzel.scriptcs -y
  - ps: $env:Path += ";C:\\Python310;C:\\Python310\\Scripts"
  - C:\Python310\python.exe -m pip install creep

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
- ps: .\BakeAndDeploy.ps1

test: off
