version: 1.0.{build}

environment:
  ftppassword:
    secure: eK/zCvZEGU6BcRfo1CoYnlrLD7SoyaUyOb3aIq8CkmQ=
    
build_script:
- ps: "Set-Culture fr-FR\r\nPretzel/Pretzel bake site"

test: off

artifacts:
- path: site/_site
  name: compiled_site

before_deploy:
- ps: .\Clear-FtpDirectory.ps1

deploy:
- provider: FTP
  host: laedit.net
  protocol: ftp
  username: zlaeditn12713ne
  password:
    secure: eK/zCvZEGU6BcRfo1CoYnlrLD7SoyaUyOb3aIq8CkmQ=
  folder: /httpdocs/readinglist
  application: site\compiled_site.zip