version: 1.0.{build}

environment:
  ftp_user:
    secure: qFoKIg/opgBgjdrHAZlFOA==
  ftp_password:
    secure: 6wrMkWW2J1r3Yhg4o1bfxkuIKwNG05EW0ZkpryokBzI=
  access_token:
    secure: WU0gFasfdrLM/783H66lbD07Sre+fVFOMf9PurC+tyjt1vKDPnWVOLz3sfUG0tcE
  publisher_id:
    secure: cGDidYlVbJZkd9Fy7m1nRw==
  publisher_password:
    secure: bh3TjAp9X66mDDJ46/g8wghjC5nce34YA3Y9EGXz+qY=
  git_mail:
    secure: bVPyDjOtyByKm9rSo/rjN79B6Z6/pI1hhbhYZHiAJ/E=

cache:
  - C:\tools\Pretzel -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
- "\"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.0\\Framework\\v4.0\\fsi\" ./scripts/Build.fsx"

test: off
