version: 1.0.{build}

environment:
  ftp_password:
    secure: 6wrMkWW2J1r3Yhg4o1bfxkuIKwNG05EW0ZkpryokBzI=
  config1:
    secure: ogDKopwS7JRJK1qlJErY72zOiNyHhSjhsahQyu33yXg=
  config2:
    secure: lBUg3wgeQWhthz06T/iCabNhj5G0mXWYF5udbfdZ92E=

before_build:
  - nuget restore src

build_script:
  - msbuild "src\AddBook.sln" /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:PublishProfile=Local /p:DeployOnBuild=True

test: off

artifacts:
- path: Publish

before_deploy:
- ps: .\Clear-FtpDirectory.ps1

deploy_script:
- ps: .\Publish.ps1