version: 1.0.{build}

environment:
  ftppassword:
    secure: eK/zCvZEGU6BcRfo1CoYng2sjeywm69Q0JpJoJBdYqA=
    
build_script:
- ps: Pretzel/Pretzel bake site

test: off

artifacts:
- path: site/_site
  name: compiled_site

deploy:
- provider: FTP
  host: laedit.net
  protocol: ftp
  username: zlaeditn12713ne
  password:
    secure: eK/zCvZEGU6BcRfo1CoYng2sjeywm69Q0JpJoJBdYqA=
  folder: /httpdocs/readinglist
  application: site\compiled_site.zip