image: Visual Studio 2019

version: 1.0.{build}

environment:
  ftp_user:
    secure: qFoKIg/opgBgjdrHAZlFOA==
  ftp_password:
    secure: 6wrMkWW2J1r3Yhg4o1bfxkuIKwNG05EW0ZkpryokBzI=

install:
  - cup pretzel -y
  - cup pretzel.scriptcs -y
  - ps: $env:Path += ";C:\\Python35;C:\\Python35\\Scripts"
  - pip install creep

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
- ps: .\BakeAndDeploy.ps1

test: off
